# Generated by Django 3.0.4 on 2020-05-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1', models.ImageField(upload_to='')),
                ('slide2', models.ImageField(upload_to='')),
                ('slide3', models.ImageField(upload_to='')),
                ('slide4', models.ImageField(upload_to='')),
            ],
        ),
    ]
