# Generated by Django 3.0.4 on 2020-05-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmodel',
            name='slide1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='indexmodel',
            name='slide2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='indexmodel',
            name='slide3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='indexmodel',
            name='slide4',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
