# Generated by Django 3.0.4 on 2020-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200512_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='apartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('desc', models.TextField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='features',
            name='desc',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
