# Generated by Django 3.0.4 on 2020-05-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200513_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmenttype',
            name='ApartmentTitle',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
